// src/features/admin/components/ward-form.tsx

"use client";

import { Building2, DoorOpen, Hospital, Layers3, Stethoscope } from "lucide-react";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";

import { Form } from "@/components/ui/form";
import {
  CheckboxField,
  EnterpriseFormActions,
  EnterpriseFormGrid,
  EnterpriseFormHero,
  EnterpriseFormNotice,
  EnterpriseFormSection,
  EnterpriseReadonlyField,
  SelectField,
  TextField,
} from "@/shared/components/enterprise";
import {
  wardFormSchema,
  type WardFormInput,
  type WardFormValues,
} from "../schemas/admin.schema";

interface WardFormProps {
  defaultValues?: Partial<WardFormInput>;
  isSubmitting?: boolean;
  onSubmit: (values: WardFormValues) => void | Promise<void>;
  onCancel?: () => void;
}

const wardTypeOptions = [
  { label: "General Ward", value: "General" },
  { label: "Intensive Care Unit", value: "ICU" },
  { label: "Emergency Observation", value: "Emergency" },
  { label: "Maternity Ward", value: "Maternity" },
  { label: "Isolation Ward", value: "Isolation" },
  { label: "Private Ward", value: "Private" },
  { label: "Semi-Private Ward", value: "Semi-Private" },
  { label: "Day Care", value: "Day Care" },
];

const floorOptions = [
  { label: "Ground Floor", value: "Ground Floor" },
  { label: "1st Floor", value: "1" },
  { label: "2nd Floor", value: "2" },
  { label: "3rd Floor", value: "3" },
  { label: "4th Floor", value: "4" },
  { label: "5th Floor", value: "5" },
];

export function WardForm({
  defaultValues,
  isSubmitting,
  onSubmit,
  onCancel,
}: WardFormProps) {
  const form = useForm<WardFormInput>({
    resolver: zodResolver(wardFormSchema),
    defaultValues: {
      name: "",
      ward_type: "General",
      floor: "",
      active: true,
      ...defaultValues,
    },
  });

  return (
    <Form {...form}>
      <form
        onSubmit={form.handleSubmit((values) =>
          onSubmit(wardFormSchema.parse(values))
        )}
        className="flex min-h-[calc(100vh-10rem)] flex-col"
      >
        <div className="space-y-5 pb-8">
          <EnterpriseFormHero
            eyebrow="Inpatient Master Data"
            title="Configure Ward"
            description="Wards organize inpatient admissions, nursing assignment, bed capacity, emergency observation, and clinical location visibility."
            icon={Hospital}
          />

          <EnterpriseFormSection
            step="1"
            icon={Building2}
            title="Ward Identity"
            description="Define how this ward appears across admissions, nursing, and bed allocation screens."
          >
            <EnterpriseFormGrid columns={2}>
              <TextField
                form={form}
                name="name"
                label="Ward Name"
                placeholder="Example: General Ward A"
                disabled={isSubmitting}
              />
              <SelectField
                form={form}
                name="ward_type"
                label="Ward Type"
                placeholder="Select ward type"
                options={wardTypeOptions}
                disabled={isSubmitting}
              />
              <SelectField
                form={form}
                name="floor"
                label="Floor"
                placeholder="Select floor"
                options={floorOptions}
                disabled={isSubmitting}
              />
              <EnterpriseReadonlyField
                label="Ward Code"
                value="Generated by backend rules after save"
                icon={DoorOpen}
                description="Used later for bed numbering, reports, and transfer workflows."
              />
            </EnterpriseFormGrid>
          </EnterpriseFormSection>

          <EnterpriseFormGrid columns={2}>
            <EnterpriseFormSection
              step="2"
              icon={Layers3}
              title="Bed Allocation"
              description="This ward becomes available for bed creation and inpatient movement workflows."
            >
              <div className="rounded-2xl border border-dashed border-slate-300 bg-slate-50 p-4 text-sm leading-6 text-slate-600">
                Beds are managed from the Beds tab after the ward is saved. Keep ward names stable once beds are assigned.
              </div>
            </EnterpriseFormSection>

            <EnterpriseFormSection
              step="3"
              icon={Stethoscope}
              title="Clinical Availability"
              description="Inactive wards are hidden from admission and allocation workflows."
            >
              <div className="rounded-2xl border border-slate-200 bg-slate-50 p-4">
                <CheckboxField
                  form={form}
                  name="active"
                  label="Ward is active and available for hospital workflows"
                  disabled={isSubmitting}
                />
              </div>
            </EnterpriseFormSection>
          </EnterpriseFormGrid>

          <EnterpriseFormNotice tone="warning">
            Before deleting or deactivating a ward, verify that no active beds,
            admissions, or transfer workflows depend on it.
          </EnterpriseFormNotice>
        </div>

        <EnterpriseFormActions
          submitText="Save Ward"
          isSubmitting={isSubmitting}
          onCancel={onCancel}
          hint="Changes will update ward master data immediately after save."
        />
      </form>
    </Form>
  );
}
